name: build
on:
  push:
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        cc: [gcc, clang]
    env:
      CC: ${{ matrix.cc == 'gcc' && 'gcc-13' || 'clang-16' }}
      CXX: ${{ matrix.cc == 'gcc' && 'g++-13' || 'clang++-16' }}
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y $CC $CXX build-essential cmake git \
            libmysqlclient-dev libreadline-dev libbz2-dev libncurses-dev zlib1g-dev \
            libboost-dev libboost-system-dev libboost-filesystem-dev \
            libboost-program-options-dev libboost-thread-dev libboost-iostreams-dev \
            libboost-regex-dev libssl-dev
      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build build -j"$(nproc)"
